version: 2
jobs:
  build:
    docker:
      # the Docker image with Cypress dependencies
      - image: cypress/browsers:chrome67
        environment:
          ## this enables colors in the output
          TERM: xterm
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-deps-{{ checksum "package-lock.json" }}
            - v2-deps-
      - run: npm ci
      - save_cache:
          key: v2-deps-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
            - ~/.npm
            - ~/.cache
      - run:
          name: Running E2E tests with Chrome
          command: npm run chrome
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots